### ISSUE TITLE
any chance you could add the functionality for badge on each bar button item ?

### ISSUE THREAD

**Issue by prakharrawat** [singer1026/IrregularTabbarCustom#1]
The original LCTabBarItem had the Badge Functionality, it would be great if you could add this to it

**Comment by singer1026** [comment]
you can do it for your self. thanks
https://github.com/JaviSoto/JSBadgeView

**Comment by singer1026** [comment]
I found a very perfect library for TabbarViewController . 
https://github.com/ChenYilong/CYLTabBarController

**Comment by prakharrawat** [comment]
Thanks Buddy, You are the best. Your library is awesome.
